name: Release

on:
  workflow_call:
    inputs:
      tags:
        type: boolean
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build/**/*  .zip"
